import Foundation
public final class OperationCoordinator: @unchecked Sendable {
    private let lock = NSLock(); private var states: [UUID: OperationSnapshot] = [:]
    public init() {}
    public func start(retryDescriptor: RetryDescriptor? = nil) -> UUID { let id = UUID(); lock.withLock { states[id] = OperationSnapshot(id: id, phase: .assessing, progress: nil, retryDescriptor: retryDescriptor, request: retryDescriptor?.request) }; return id }
    public func retry(id: UUID) -> OperationSnapshot? { lock.withLock { guard let prior = states[id], prior.phase == .failed || prior.phase == .cancelled, let descriptor = prior.retryDescriptor, descriptor.currentAttempt < descriptor.maxAttempts else { return nil }; let next = RetryDescriptor(request: OperationRequestToken(UUID().uuidString), originalRequest: descriptor.originalRequest, currentAttempt: descriptor.currentAttempt + 1, maxAttempts: descriptor.maxAttempts, delayNanoseconds: descriptor.delayNanoseconds); let snapshot = OperationSnapshot(id: UUID(), phase: .assessing, progress: nil, retryDescriptor: next, request: next.request); states[snapshot.id] = snapshot; return snapshot } }
    @discardableResult public func update(id: UUID, phase: OperationPhase, progress: OperationProgress?, failure: OperationFailure? = nil) -> Bool { lock.withLock { guard let current = states[id], !current.phase.terminal else { return false }; let legal: Set<OperationPhase> = { switch current.phase { case .assessing: return [.awaitingConsent, .provisioning, .downloading, .processing, .failed, .cancelled]; case .awaitingConsent: return [.provisioning, .failed, .cancelled]; case .provisioning: return [.downloading, .processing, .completed, .failed, .cancelled]; case .downloading: return [.verifying, .failed, .cancelled]; case .verifying: return [.processing, .failed, .cancelled]; case .processing: return [.committing, .completed, .failed, .cancelled]; case .committing: return [.completed, .failed, .cancelled]; default: return [] } }(); guard legal.contains(phase) else { return false }; states[id] = OperationSnapshot(id: id, phase: phase, progress: progress, failure: failure, retryDescriptor: current.retryDescriptor, request: current.request); return true } }
    @discardableResult public func updateProgress(id: UUID, progress: OperationProgress) -> Bool { lock.withLock { guard let current = states[id], !current.phase.terminal else { return false }; states[id] = OperationSnapshot(id: id, phase: current.phase, progress: progress, failure: current.failure, retryDescriptor: current.retryDescriptor, request: current.request); return true } }
    public func snapshot(id: UUID) -> OperationSnapshot? { lock.withLock { states[id] } }
}
