#!/usr/bin/env python3
"""Cut each pick to one clean shot (no scene cut inside) and export it as a JPEG sequence + js/seq.js manifest.

usage: tools/seq.py            (all picks)
       tools/seq.py name ...   (only these)
"""
import json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FOOT = os.path.join(ROOT, "..", "research", "footage")
OUT = os.path.join(ROOT, "assets", "seq")
FPS, WIDTH, MAXLEN = 30, 640, 2.4

# name: (source, around-time seconds)
PICKS = {
    "switchboard": ("tools/diplomats1965.mpeg", 320),
    "operator": ("tools/diplomats1965.mpeg", 358),
    "telegraph": ("tools/telegram1956.mpeg", 52),
    "sounder": ("tools/telegram1956.mpeg", 60),
    "ticker": ("tools/telegram1956.mpeg", 377),
    "teleprinter": ("tools/telegram1956.mpeg", 308),
    "keys": ("tools/telegram1956.mpeg", 412),
    "drawers": ("tools/library1951.m4v", 195),
    "cards": ("tools/library1951.m4v", 227),
    "card": ("tools/library1951.m4v", 258),
    "console": ("tools/computers1957.mp4", 437),
    "reels": ("tools/computers1957.mp4", 556),
    "typists": ("tools/secretary1941.mpeg", 50),
    "smith": ("blacksmith1893.mp4", 8),
    "forge": ("blacksmith1893.mp4", 5.0, 640),
    "pour": ("MasterHa1936_2.mpeg", 38.6, 1440),
    "ladle": ("MasterHa1936_2.mpeg", 299.6, 1440),
    "crucible": ("../../assets/v/crucible.mp4", 0.4),
    "liftoff": ("../../assets/v/app-liftoff.mp4", 0.7),
    "gallop": ("icons/Horse_in_Motion_-_Sallie_Gardner_(animation).webm", -1, 1440),
    "ladder": ("nasa-a11-broll.mp4", 1374.5, 1280),
    "aldrin": ("nasa-a11-broll.mp4", 1384, 1280),
    "eva": ("icons/Restored_Apollo_11_Moonwalk_-_Original_NASA_EVA_Mission_Video_-_Walking_on_the_Moon.webm", 1100, 1440, "crop=1440:1080:240:0"),
    "flag": ("nasa-a11-broll.mp4", 1458, 1280),
    "ignition": ("nasa-a11-broll.mp4", 708, 1280),
    "ascent": ("nasa-a11-broll.mp4", 864, 1280),
    "earthorbit": ("nasa-a11-broll.mp4", 1056, 1280),
    "splash": ("nasa-a11-broll.mp4", 1908, 1280),
    "crowd": ("nasa-a11-broll.mp4", 684, 1280),
    "moonface": ("icons/Le_Voyage_dans_la_Lune_(1902).webm", 368, 1440),
    "capsule": ("icons/Le_Voyage_dans_la_Lune_(1902).webm", 336, 1440),
    "train": ("icons/Arrival_of_a_Train_at_La_Ciotat_(The_Lumière_Brothers,_1895).webm", 14, 540),
    "arrival": ("icons/Arrival_of_a_Train_at_La_Ciotat_(The_Lumière_Brothers,_1895).webm", 9.2, 540, "", 3.2),
}


def cuts(src, a, b):
    cmd = ["ffmpeg", "-v", "info", "-ss", str(a), "-t", str(b - a), "-i", src, "-an",
           "-vf", "select='gt(scene,0.28)',showinfo", "-f", "null", "-"]
    err = subprocess.run(cmd, capture_output=True, text=True).stderr
    return [a + float(m) for m in re.findall(r"pts_time:([0-9.]+)", err)]


def shot(src, t):
    if t < 0:
        return 0, 60
    a, b = max(0, t - 4), t + 6
    cs = [a] + cuts(src, a, b) + [b]
    for s, e in zip(cs, cs[1:]):
        if s <= t < e:
            s, e = s + 0.12, e - 0.12
            if e - s > MAXLEN:
                mid = min(max(t, s + MAXLEN / 2), e - MAXLEN / 2)
                s, e = mid - MAXLEN / 2, mid + MAXLEN / 2
            return s, e
    return t, t + MAXLEN


def export(name, src, t, width=WIDTH, pre="", dur=None):
    path = os.path.join(FOOT, src)
    s, e = (t, t + dur) if dur else shot(path, t)
    d = os.path.join(OUT, name)
    os.makedirs(d, exist_ok=True)
    for f in os.listdir(d):
        os.remove(os.path.join(d, f))
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-ss", f"{s:.3f}", "-t", f"{e - s:.3f}", "-i", path, "-an",
                    "-vf", (pre + "," if pre else "") + f"yadif=deint=interlaced,scale=trunc(iw*sar/2)*2:ih,setsar=1,fps={FPS},scale={width}:-2:flags=lanczos", "-q:v", "3",
                    os.path.join(d, "%03d.jpg")], check=True)
    n = len([f for f in os.listdir(d) if f.endswith(".jpg")])
    probe = subprocess.run(["ffprobe", "-v", "error", "-select_streams", "v", "-show_entries", "stream=width,height",
                            "-of", "csv=p=0", os.path.join(d, "001.jpg")], capture_output=True, text=True).stdout
    w, h = map(int, probe.strip().split(","))
    print(f"{name:12s} {s:8.2f}-{e:8.2f}  {n} frames  {w}x{h}")
    return {"n": n, "w": w, "h": h, "src": src, "in": round(s, 3)}


def main():
    man_path = os.path.join(ROOT, "js", "seq.js")
    man = {}
    if os.path.exists(man_path):
        man = json.loads(open(man_path).read().split("=", 1)[1].rstrip(";\n"))
    want = sys.argv[1:] or list(PICKS)
    for name in want:
        man[name] = export(name, *PICKS[name])
    with open(man_path, "w") as f:
        f.write("// generated by tools/seq.py\nwindow.SEQ = " + json.dumps(man) + ";\n")


if __name__ == "__main__":
    main()
