import AppKit

struct PasteboardSnapshot { let types: [NSPasteboard.PasteboardType]; let payload: ClipboardPayload; let sourceBundleIdentifier: String? }
protocol PasteboardClient: AnyObject { var changeCount: Int { get }; func snapshot() -> PasteboardSnapshot?; func write(_ payload: ClipboardPayload) }
final class SystemPasteboardClient: PasteboardClient {
    let pasteboard: NSPasteboard
    init(_ pasteboard: NSPasteboard = .general) { self.pasteboard = pasteboard }
    var changeCount: Int { pasteboard.changeCount }
    func snapshot() -> PasteboardSnapshot? {
        let types = pasteboard.types ?? []
        let hostile = types.map(\.rawValue).contains { $0.localizedCaseInsensitiveContains("concealed") || $0.localizedCaseInsensitiveContains("transient") || $0.localizedCaseInsensitiveContains("autogenerated") || $0.localizedCaseInsensitiveContains("password") || $0.localizedCaseInsensitiveContains("foundry") }
        guard !hostile else { return nil }
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL], !urls.isEmpty { return PasteboardSnapshot(types: types, payload: .files(urls), sourceBundleIdentifier: NSWorkspace.shared.frontmostApplication?.bundleIdentifier) }
        if let value = pasteboard.string(forType: .string), !value.isEmpty { return PasteboardSnapshot(types: types, payload: .text(value), sourceBundleIdentifier: NSWorkspace.shared.frontmostApplication?.bundleIdentifier) }
        return nil
    }
    func write(_ payload: ClipboardPayload) { pasteboard.clearContents(); switch payload { case .text(let v): pasteboard.setString(v, forType: .string); case .files(let v): pasteboard.writeObjects(v as [NSURL]); case .image(let d): pasteboard.setData(d, forType: .tiff) } }
}
